import React, { useState } from 'react'
import Login from './pages/Login.jsx'
import Dashboard from './pages/Dashboard.jsx'
import Tasks from './pages/Tasks.jsx'
import Announcements from './pages/Announcements.jsx'
import AdminPanel from './pages/AdminPanel.jsx'
import Sales from './pages/Sales.jsx'
import Waste from './pages/Waste.jsx'
import KPI from './pages/KPI.jsx'
import Leaderboard from './pages/Leaderboard.jsx'
import ChangePassword from './pages/ChangePassword.jsx'
import TasksCompliance from './pages/TasksCompliance.jsx'
import Maintenance from './pages/Maintenance.jsx'
